// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module "vue" {
  export interface GlobalComponents {
    BaseInfo: typeof import("./src/components/Setting/baseInfo.vue")["default"];
    CheckPass: typeof import("./src/components/Setting/checkPass.vue")["default"];
    Header: typeof import("./src/components/Header/index.vue")["default"];
    Pagination: typeof import("./src/components/Pagination/index.vue")["default"];
    SideBar: typeof import("./src/components/SideBar/index.vue")["default"];
    Tags: typeof import("./src/components/Tags/index.vue")["default"];
    VersionLog: typeof import("./src/components/Setting/versionLog.vue")["default"];
  }
}

export {};
