// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    403: typeof import('./src/components/abnormal/403.vue')['default']
    404: typeof import('./src/components/abnormal/404.vue')['default']
    Analysis: typeof import('./src/components/dashboard/analysis.vue')['default']
    AppConfig: typeof import('./src/components/appConfig/index.vue')['default']
    BaseInfo: typeof import('./src/components/dropDownItem/baseInfo.vue')['default']
    Build: typeof import('./src/components/abnormal/build.vue')['default']
    CardList: typeof import('./src/components/template/cardList.vue')['default']
    CheckPass: typeof import('./src/components/dropDownItem/checkPass.vue')['default']
    ComputerMonitor: typeof import('./src/components/computerMonitor/index.vue')['default']
    Copy: typeof import('./src/components/copy/index.vue')['default']
    DialogDrag: typeof import('./src/components/dialogDrag/index.vue')['default']
    EasyForm: typeof import('./src/components/template/easyForm.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ErrorTip: typeof import('./src/components/tips/errorTip.vue')['default']
    FeedbackCenter: typeof import('./src/components/message/feedbackCenter.vue')['default']
    I18n: typeof import('./src/components/i18n/index.vue')['default']
    InfiniteScroll: typeof import('./src/components/infiniteScroll/index.vue')['default']
    Markdown: typeof import('./src/components/editor/markdown.vue')['default']
    NetworkError: typeof import('./src/components/abnormal/networkError.vue')['default']
    NoviceGuide: typeof import('./src/components/noviceGuide/index.vue')['default']
    Pagination: typeof import('./src/components/Pagination/index.vue')['default']
    QrCode: typeof import('./src/components/qrCode/index.vue')['default']
    SuccessTip: typeof import('./src/components/tips/successTip.vue')['default']
    TableOperation: typeof import('./src/components/template/tableOperation.vue')['default']
    TextEditor: typeof import('./src/components/editor/textEditor.vue')['default']
    VersionLog: typeof import('./src/components/dropDownItem/versionLog.vue')['default']
    WarningTip: typeof import('./src/components/tips/warningTip.vue')['default']
    Watermark: typeof import('./src/components/watermark/index.vue')['default']
    Workbench: typeof import('./src/components/dashboard/workbench.vue')['default']
  }
}

export { }
